#### 1.- Import the NUMPY package under the name np.

In [1]:
import numpy as np

#### 2.- Print the NUMPY version and the configuration.

In [3]:
print(np.version.version)

1.21.0


#### 3.- Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a". Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find. Print a

In [33]:
# 1.-
a_1 = np.random.random((2, 3, 5))
a_1

array([[[0.12050588, 0.40776605, 0.12249744, 0.86140904, 0.57384674],
        [0.45247417, 0.59465225, 0.7351169 , 0.69663346, 0.36805872],
        [0.03574943, 0.22959237, 0.18871731, 0.51949819, 0.02614254]],

       [[0.24330015, 0.83578299, 0.37107843, 0.24608776, 0.12703523],
        [0.27614923, 0.05536305, 0.64462192, 0.67409299, 0.00965216],
        [0.34555729, 0.46962599, 0.10100447, 0.86209479, 0.78358437]]])

In [34]:
# 3.- 
a_2 = np.random.random(30).reshape(2, 3, 5)
a_2

array([[[0.26802817, 0.53359042, 0.26397401, 0.86041552, 0.79785231],
        [0.43958104, 0.9858923 , 0.40378786, 0.3929786 , 0.42465148],
        [0.75199062, 0.87563648, 0.62304009, 0.88144283, 0.7624334 ]],

       [[0.5159259 , 0.99523376, 0.54558014, 0.45800733, 0.88922872],
        [0.20846266, 0.64729239, 0.3212027 , 0.13642272, 0.59748819],
        [0.18911519, 0.13085156, 0.25729076, 0.09902737, 0.29642137]]])

#### 4.- Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable "b". Print b.

In [35]:
b = np.full((5, 2, 3), 1, dtype = int)
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 5.- Do a and b have the same size? How do you prove that in Python code?

In [44]:
if a_1.shape == b.shape:
    print(True)
    print('a and b have the same size')
else:
    print(False)
    print('a and b DO NOT have the same size')
    print(f'Dimensions of a are: {a_1.shape}')
    print(f'Dimensions of b are: {b.shape}')

False
a and b DO NOT have the same size
Dimensions of a are: (2, 3, 5)
Dimensions of b are: (5, 2, 3)


#### 6.- Are you able to add a and b? Why or why not?

In [37]:
# Matrices do not have the same dimensions
c = a_1 + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 7.- Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [52]:
x = np.ones((1, 2, 3))
print(x)
print(x.shape)

y = np.transpose(x, (1, 0, 2))
print(y)
print(y.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]]
(1, 2, 3)
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
(2, 1, 3)


In [56]:
c = np.transpose(b, (1, 2, 0))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 8.- Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [58]:
d = a_1 + c
print(d)

[[[1.12050588 1.40776605 1.12249744 1.86140904 1.57384674]
  [1.45247417 1.59465225 1.7351169  1.69663346 1.36805872]
  [1.03574943 1.22959237 1.18871731 1.51949819 1.02614254]]

 [[1.24330015 1.83578299 1.37107843 1.24608776 1.12703523]
  [1.27614923 1.05536305 1.64462192 1.67409299 1.00965216]
  [1.34555729 1.46962599 1.10100447 1.86209479 1.78358437]]]


#### 9.- Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

c was transposed into a configuration that made possible the addition of a and itself. Thus, the relation between d and a is c, is it is a "1-only" matrix, so the only difference is the ones that were added.

#### 10.- Multiply a and c. Assign the result to e.

In [61]:
e = a_1*c
print(e)

[[[0.12050588 0.40776605 0.12249744 0.86140904 0.57384674]
  [0.45247417 0.59465225 0.7351169  0.69663346 0.36805872]
  [0.03574943 0.22959237 0.18871731 0.51949819 0.02614254]]

 [[0.24330015 0.83578299 0.37107843 0.24608776 0.12703523]
  [0.27614923 0.05536305 0.64462192 0.67409299 0.00965216]
  [0.34555729 0.46962599 0.10100447 0.86209479 0.78358437]]]


#### 11.- Does e equal to a? Why or why not?

Of course no. Something times one equals the number itself, which is totally different to adding 1 to a number which increases the value of that number by 1.

#### 12.- Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [62]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 13.-Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [91]:
f = np.empty([2, 3, 5])
print(f)

[[[0.12050588 0.40776605 0.12249744 0.86140904 0.57384674]
  [0.45247417 0.59465225 0.7351169  0.69663346 0.36805872]
  [0.03574943 0.22959237 0.18871731 0.51949819 0.02614254]]

 [[0.24330015 0.83578299 0.37107843 0.24608776 0.12703523]
  [0.27614923 0.05536305 0.64462192 0.67409299 0.00965216]
  [0.34555729 0.46962599 0.10100447 0.86209479 0.78358437]]]


#### 14. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f. If a value equals to d_mean, assign 50 to the corresponding value in f. Assign 0 to the corresponding value(s) in f for d_min in d. Assign 100 to the corresponding value(s) in f for d_max in d. In the end, f should have only the following values: 0, 25, 50, 75, and 100. Note: you don't have to use Numpy in this question.

In [94]:
for matrix in range(d.shape[0]):
    for row in range(d.shape[1]):
        for num in range(d.shape[2]):
            x = d[matrix][row][num]
            if x > d_min and x < d_mean:
                f[matrix, row, num] = 25
            elif x > d_mean and x < d_max:
                f[matrix, row, num] = 75
            elif x == d_mean:
                f[matrix, row, num] = 50
            elif x == d_min:
                f[matrix, row, num] = 0
            elif x == d_max:
                f[matrix, row, num] = 100

In [95]:
f

array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  25.],
        [ 25.,  25.,  25.,  75.,  25.]],

       [[ 25.,  75.,  25.,  25.,  25.],
        [ 25.,  25.,  75.,  75.,   0.],
        [ 25.,  75.,  25., 100.,  75.]]])

#### 15.- Print d and f. Do you have your expected f?<br>
#### For instance, if your d is:<br>
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],<br>
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],<br>
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],<br>
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],<br>
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],<br>
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])<br>
        
#### Your f should be:<br>
array([[[ 75.,  75.,  75.,  25.,  75.],<br>
        [ 75.,  75.,  25.,  25.,  25.],<br>
        [ 75.,  25.,  75.,  75.,  75.]],<br>
       [[ 25.,  25.,  25.,  25., 100.],<br>
        [ 75.,  75.,  75.,  75.,  75.],<br>
        [ 25.,  75.,   0.,  75.,  75.]]])<br>


#### 18.- Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values <br>
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:<br>
array([[[ 'D',  'D',  'D',  'B',  'D'],<br>
        [ 'D',  'D',  'B',  'B',  'B'],<br>
        [ 'D',  'B',  'D',  'D',  'D']],<br>
       [[ 'B',  'B',  'B',  'B',  'E'],<br>
        [ 'D',  'D',  'D',  'D',  'D'],<br>
        [ 'B',  'D',   'A',  'D', 'D']]])<br>

Again, you don't need Numpy in this question.<br>

In [107]:
f = np.empty((2, 3, 5)).tolist()

In [108]:
for matrix in range(d.shape[0]):
    for row in range(d.shape[1]):
        for num in range(d.shape[2]):
            x = d[matrix][row][num]
            if x > d_min and x < d_mean:
                f[matrix][row][num] = 'B'
            elif x > d_mean and x < d_max:
                f[matrix][row][num] = 'D'
            elif x == d_mean:
                f[matrix][row][num] = 'C'
            elif x == d_min:
                f[matrix][row][num] = 'A'
            elif x == d_max:
                f[matrix][row][num] = 'E'

In [109]:
f

[[['B', 'D', 'B', 'D', 'D'],
  ['D', 'D', 'D', 'D', 'B'],
  ['B', 'B', 'B', 'D', 'B']],
 [['B', 'D', 'B', 'B', 'B'],
  ['B', 'B', 'D', 'D', 'A'],
  ['B', 'D', 'B', 'E', 'D']]]